"use strict";

try {
    let x = 10;
} catch (error) { //se captura el error
    console.log(error); // Se manda a imprimir
}

//Opcional
/*finally{
    console.log('Termina la revisi√≥n de errores');
} */

console.log('Hola Mundo')